# Generated by Django 4.2.3 on 2023-07-19 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speaker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speaker',
            name='areas_of_expertise',
        ),
        migrations.RemoveField(
            model_name='speaker',
            name='contact_info',
        ),
        migrations.RemoveField(
            model_name='speaker',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='speaker',
            name='photo',
            field=models.ImageField(default='10', upload_to='speakers/'),
        ),
        migrations.AddField(
            model_name='speaker',
            name='twitter_handle',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='speaker',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
