# Generated by Django 4.2.3 on 2023-07-18 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conferences', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('job_role', models.CharField(choices=[('Full Stack', 'Full Stack'), ('Backend', 'Backend'), ('Frontend', 'Frontend'), ('Designer', 'Designer'), ('Student', 'Student')], max_length=20)),
                ('topics_interest', models.CharField(choices=[('JavaScript Frameworks', 'JavaScript Frameworks'), ('JavaScript Libraries', 'JavaScript Libraries'), ('Node.js', 'Node.js'), ('Build Tools', 'Build Tools')], max_length=100)),
                ('payment_card_number', models.CharField(max_length=16)),
                ('zip_code', models.CharField(max_length=10)),
                ('cvv', models.CharField(max_length=4)),
                ('expiration_date', models.CharField(max_length=5)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='conferences.conference')),
            ],
        ),
    ]
